Add color to `alloinit`

diff --git a/alloinit b/alloinit
--- a/alloinit
+++ b/alloinit
@@ -20,17 +20,34 @@ set -o pipefail
 # Data directory.
 data_home="${XDG_DATA_HOME:-$HOME/.local/share}/alloinit"
 
+# Color support if outputting to a terminal with color.
+if [[ -t 1 ]] && [[ -n "$(tput colors)" ]] ; then
+    bold="$(tput bold)"
+    underline="$(tput smul)"
+    normal="$(tput sgr0)"
+    red="$(tput setaf 1)"
+    green="$(tput setaf 2)"
+    yellow="$(tput setaf 3)"
+    blue="$(tput setaf 4)"
+fi
+
 # Name of the script.
 name="$(basename $0)"
+# Version.
+version='0.1.0'
 # Usage information.
-usage="$0
-One-step Allolib project initializer.
 
-Usage:
-    $name [-l <lib_dir>] <dir>      # Start a new Allolib project in <dir>.
-    $name [-l <lib_dir>] -r <dir>   # Relink Allolib dependencies in <dir>.
-    $name [-l <lib_dir>] -u         # Update Allolib dependencies.
-    $name [-l <lib_dir>] -L         # Just install Allolib dependencies.
+function show_usage() {
+    local width="$(tput cols)"
+    # Color shortcuts.
+    local n="$normal"
+    local b="$blue"
+    local u="$underline"
+    local g="$green"
+    local y="$yellow"
+    fold -s -w $((width > 80 ? 80 : width)) <<EOF
+$g$0$n $version
+One-step Allolib project initializer.
 
 Start a new Allolib project in the directory <dir>. The generated project is a \
 configured clone of allotemplate, with the \`origin\` remote unset and the \
@@ -40,22 +57,26 @@ of Allolib extensions)--are shared between projects created by $name using \
 symbolic links, saving disk space and obviating the need to recursively \
 download dependencies whenever starting a new allolib project. If the \
 dependency directories are moved, then the symbolic links will need to be \
-relinked using the flag -r.
+relinked using the flag $g-r$n.
 
-Options:
-    -l <lib_dir>    Specify the directory to install allolib dependencies to.
-                    [Default: $data_home]
-    -r              Relink dependencies. Useful if you have moved <lib_dir>.
-    -u              Update dependencies.
-    -L              Install dependencies without initializing a project.
-    -h              Show this help text.
+${y}Usage$n:
+    $g$name [-l <libs>] <dir>$n    Start a new Allolib project in <dir>.
+    $g$name [-l <libs>] -r <dir>$n Relink Allolib dependencies in <dir>.
+    $g$name [-l <libs>] -u$n       Update Allolib dependencies.
+    $g$name [-l <libs>] -L$n       Just install Allolib dependencies.
 
-Full Documentation:
-    https://allolib-s22.github.io/notes-ethwu/alloinit.html"
+${y}Options$n:
+    $g-l <libs>$n   Specify the directory to install Allolib dependencies
+                to. [Default: $g$data_home$n]
+    $g-r$n          Relink dependencies. Useful if you have moved Allolib.
+    $g-u$n          Update dependencies.
+    $g-L$n          Install dependencies without initializing a project.
+    $g-h$n          Show this help text.
+    $g-V$n          Show the version.
 
-function show_usage() {
-    width="$(tput cols)"
-    echo "$usage" | fold -s -w $((width > 80 ? 80 : width))
+${y}Full Documentation$n:
+    $b${u}https://allolib-s22.github.io/notes-ethwu/alloinit.html$n
+EOF
 }
 
 if [[ $# -lt 1 ]] ; then
@@ -68,7 +89,7 @@ args=()
 # Subcommand to execute.
 subcommand=init
 while [[ $OPTIND -le $# ]] ; do
-    if getopts 'l:ruLh' opt ; then
+    if getopts 'l:ruLhV' opt ; then
         case "$opt" in
         l)
             lib="$OPTARG"
@@ -86,6 +107,10 @@ while [[ $OPTIND -le $# ]] ; do
             show_usage
             exit 0
             ;;
+        V)
+            echo "$version"
+            exit 0
+            ;;
         ?)
             exit 1
             ;;
@@ -97,10 +122,23 @@ while [[ $OPTIND -le $# ]] ; do
     fi
 done
 
+# Log a success message to stderr, in bold green if the output is a terminal
+# that supports color.
+function success() { >&2 echo "$bold$green$*$normal" ; }
+# Log an info message to stderr, in blue if the output is a terminal that
+# supports color.
+function info() { >&2 echo "$blue$*$normal" ; }
+# Log a warning message to stderr, in yellow if the output is a terminal that
+# supports color.
+function warn() { >&2 echo "$yellow$*$normal" ; }
+# Log an error message to stderr, in bold red if the output is a terminal that
+# supports color.
+function error() { >&2 echo "$bold$red$*$normal" ; }
+
 # Directory to set up allolib project in.
 dest="${args[0]}"
 if [[ $subcommand =~ (init|relink) ]] && [[ -z "$dest" ]] ; then
-    >&2 echo 'ERROR: Project directory required.'
+    error "ERROR: Project directory required."
     >&2 show_usage
     exit 1
 fi
@@ -120,10 +158,10 @@ tmpfile=.alloinit.tmp
 # Clean up in case of early abort.
 function cleanup() {
     if [[ $subcommand == init ]] ; then
-        >&2 echo "Could not finish; cleaning up."
+        warn 'Could not finish; cleaning up.'
         for dep in "${deps[@]}" ; do
             if [[ -f "$lib/.$dep$tmpfile" ]] ; then
-                >&2 echo "Removing dependency \`$lib/$dep\`."
+                info "Removing dependency \`$lib/$dep\`."
                 rm -rf "$lib/$dep" "$lib/.$dep$tmpfile"
             fi
         done
@@ -135,7 +173,7 @@ function cleanup() {
         fi
 
         if [[ -f "$dest/$tmpfile" ]] ; then
-            >&2 echo "Removing project \`$dest\`."
+            info "Removing project \`$dest\`."
             rm -rf "$dest"
         fi
     fi
@@ -148,11 +186,10 @@ function onexit() {
 }
 
 # Indent the output of subcommands and send output to stderr.
-function indent() {
-    sed -ur "s/(^|\r)/\1\t/g" >&2
-}
+function indent() { sed -ur "s/(^|\r)/\1\t/g" >&2 ; }
 
 trap onexit EXIT
+
 
 # Install allolib dependencies to $lib.
 function install_dependencies() {
@@ -160,7 +197,7 @@ function install_dependencies() {
     for dep in "${deps[@]}" ; do
         if [[ ! -d "$lib/$dep" ]] ; then
             touch "$lib/.$dep$tmpfile" || exit $?
-            >&2 echo "Retrieving dependency \`$dep\`:"
+            info "Retrieving dependency \`$dep\`:"
             git clone "git@github.com:Allosphere-Research-Group/$dep.git" "$lib/$dep" \
                 --recurse-submodules \
                 --progress 2>&1 | indent || exit $?
@@ -177,7 +214,7 @@ function link_dependencies() {
     for dep in "${deps[@]}" ; do
         loc="$(readlink -f "$lib/$dep")" || exit $?
         [[ -z $write_gitignore ]] || printf "/$dep\n" >> "$dest/.gitignore"
-        >&2 echo "Linking dependency \`$dep\` to \`$loc\`."
+        info "Linking dependency \`$dep\` to \`$loc\`."
         ln -sf "$loc" "$dest" || exit $?
     done
 }
@@ -186,19 +223,20 @@ function link_dependencies() {
 # Execute subcommand:
 case $subcommand in
 relink)
-    >&2 echo "Relinking dependencies in project \`$dest\`."
+    info "Relinking dependencies in project \`$dest\`."
     # Install and link dependencies again, but do not write to `.gitignore`.
     install_dependencies
     link_dependencies
+    success "Successfully relinked dependencies in \`$dest\`!"
     ;;
 update)
     # Update existing libraries.
     for dep in "${deps[@]}" ; do
         if ! [[ -d "$lib/$dep" ]] ; then
-            >&2 echo "ERROR: \`$dep\` not installed in \`$lib\`."
+            error "ERROR: \`$dep\` not installed in \`$lib\`."
             exit 1
         fi
-        >&2 echo "Updating dependency \`$dep\`:"
+        info "Updating dependency \`$dep\`:"
         (
             cd "$lib/$dep"
             # Sync upstream changes to the URL of submodules.
@@ -209,17 +247,19 @@ update)
             git pull --progress || exit $?
         ) 2>&1 | indent || exit $?
     done
+    success "Successfully updated Allolib dependencies in \`$lib\`!"
     ;;
 installdeps)
     install_dependencies
+    success "Successfully installed Allolib dependencies to \`$lib\`!"
     ;;
 init)
     if [[ -d "$dest" ]] ; then
-        >&2 echo "Directory \`$dest\` already exists."
+        error "Directory \`$dest\` already exists."
         exit 1
     fi
 
-    >&2 echo "Initializing allolib project in \`$dest\`:"
+    info "Initializing allolib project in \`$dest\`:"
     mkdir -p "$dest" || exit $?
     # Mark that $dest is currently being initialized. Used for checking whether
     # to delete it in case of an early exit.
@@ -243,13 +283,12 @@ init)
     install_dependencies
     link_dependencies write_gitignore
 
-    >&2 echo 'Configuring allolib project.'
+    info 'Configuring allolib project.'
     (cd "$dest" && ./configure.sh ) 2>&1 | indent || exit $?
 
-    >&2 echo 'Removing unusable scripts (init.sh; distclean.sh).'
+    info 'Removing unusable scripts (init.sh; distclean.sh).'
     rm "$dest/"{init,distclean}.sh || exit $?
 
-    >&2 echo "Allolib project initialized successfully in \`$dest\`."
+    success "Successfully initialized Allolib project \`$dest\`!"
     ;;
 esac
-
